doc: Context IA
Aparking/BaseConocimiento pull request #27
Opened 2024-04-06 11:58 UTC by MarioArocaPaez

2024-04-06 12:17 UTC, 3ralon requested changes
Está genial @MarioArocaPaez, lo que sí que intentaría añadir sería una contextualización a la propia IA. Algo como:

_"Imagina que eres un ingeniero de software experimentado en el desarrollo de aplicaciones y sistemas. Te voy a proporcionar información sobre un proyecto de desarrollo para contextualizarte ..."_

2024-04-07 08:24 UTC, MarioArocaPaez commented
Ya está cambiado @3ralon :sunglasses:
![imagen](https://github.com/Aparking/BaseConocimiento/assets/73229438/7a8c6b1e-90dc-4c0b-abfe-5b80e9fc60e6)

2024-04-07 08:30 UTC, laurolmer approved these changes
like

2024-04-07 14:15 UTC, 3ralon approved these changes
Ahora lo veo genial!

2024-04-07 14:15 UTC, merged